### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by HolographicWings** [CPunch/ConvoBot#1]
Hello, i have an AssertionError when i launch the train.py
`Loading dataset...
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 3816.47it/s]
dataset has 7 tokens
Training...
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    gpt2.finetune(sess, main_dataset, accumulate_gradients=1, use_memory_saving_gradients=True, model_name=model_name, save_every=500, steps=1000) # steps is max number of training steps
  File "/usr/local/lib/python3.7/dist-packages/gpt_2_simple/gpt_2.py", line 342, in finetune
    feed_dict={context: sample_batch()})
  File "/usr/local/lib/python3.7/dist-packages/gpt_2_simple/gpt_2.py", line 309, in sample_batch
    return [data_sampler.sample(1024) for _ in range(batch_size)]
  File "/usr/local/lib/python3.7/dist-packages/gpt_2_simple/gpt_2.py", line 309, in <listcomp>
    return [data_sampler.sample(1024) for _ in range(batch_size)]
  File "/usr/local/lib/python3.7/dist-packages/gpt_2_simple/src/load_dataset.py", line 85, in sample
    length)
AssertionError: Dataset files are too small to sample 1024 tokens at a time`

**Comment by HolographicWings** [comment]
I have found the issue, there is no dataset
i have download a dataset from https://storage.googleapis.com/gpt-2/output-dataset/v1/small-117M.valid.jsonl
replaced "complete-data" by this file and the train.py is working
